from math import floor

MQTT_GAME_SERVER = "test.mosquitto.org"
FPS = 60

WIDTH = 1600 #1366
HEIGHT = 975#768
ARENA_BORDER = 120
ARENA_HEIGHT = HEIGHT - ARENA_BORDER

size = [WIDTH, HEIGHT]
TARGETS = 12
COLUMNS = floor((WIDTH/TARGETS))

COLUMN_LEFT_COORDS = [0,0,COLUMNS,HEIGHT]
COLUMN_RIGHT_COORDS = [WIDTH - COLUMNS,0,COLUMNS,HEIGHT]
BYTE_LAUNCHER_HEIGHT =  HEIGHT/12
BYTE_LAUNCHER_WIDTH = WIDTH - (COLUMNS*2)
SPRITE_STEP_RATE = COLUMNS

POWER_UP_WIDTH = 300

PLAYER_HEIGHT = ARENA_BORDER//2-10

STACK_HEIGHT = 10
STACK_LEVELS = 3

PU_TIME_MIN = 5
PU_TIME_MAX = 20

BASE_POINTS = 10
STACK_POINTS = 100

BYTE_DELAY = 200

STATUS_BLINK_TIME = 300

#Player Settings
PLAYER_MOVE_RIGHT = 1
PLAYER_MOVE_LEFT = -1

#Global Game Settings
GAME_START_COUNTDOWN = 3 #3 seconds

#Joystick Constants iBuffalo USB Gamepad 
JOY_X_AXIS = 0
JOY_Y_AXIS = 1

JOY_Y_BUTTON = 3
JOY_X_BUTTON = 2
JOY_A_BUTTON = 0
JOY_B_BUTTON = 1
JOY_SELECT_BUTTON = 7
JOY_START_BUTTON = 6
JOY_L_BUTTON = 4
JOY_R_BUTTON = 5

#Motion Values per axis
JOY_X_AXIS_LEFT = -1
JOY_X_AXIS_RIGHT = 1
JOY_Y_AXIS_UP = -1
JOY_Y_AXIS_DOWN = 1

BYTE_WINDOW_WIDTH = 300
BYTE_WINDOW_HEIGHT = 50

DIRECTION_RISING = -1
DIRECTION_FALLING = 1

JOYSTICK_FILE = "joystick.bbs"

SCORE_FILE = "scores.bbs"
SCORE_LIMIT = 10

PLAYER_1_DIRECTION = DIRECTION_RISING
PLAYER_2_DIRECTION = DIRECTION_FALLING

PLAYER_1_BOARDER = ARENA_BORDER
PLAYER_2_BOARDER = ARENA_HEIGHT

PLAYER_1 = 1
PLAYER_2 = 2

POWERUP_LOCKOUT_SECONDS = 5

#Timers
GAME_TIMER_EXPIRED = 22 #event id for starting the game timer

# Define some colors
BLACK    = (0x00, 0x00, 0x00)
WHITE    = (0xFF, 0xFF, 0xFF)
GREEN    = (0x00, 0xFF, 0x00)
RED      = (0xFF, 0x00, 0x00)
BLUE     = (0x00, 0x00, 0xFF)
YELLOW   = (0xFF, 0xFF, 0x00)
DARK_GREY = (38, 39, 40)
PURPLE = (0x80, 0x00, 0xFF)
GREY = (54, 56, 58)
COLOR_BACKGROUND = (108, 112, 96)
COLOR_PINK_BACKGROUND = (255, 0, 127)


SPEED_COLOR_1 = WHITE
SPEED_COLOR_2 = YELLOW
SPEED_COLOR_3 = (0xFF, 0x80, 0x00)
SPEED_COLOR_4 = RED
SPEED_COLOR_5 = (0xA2, 0x00, 0x00)

COLOR_COL_LEFT = (109, 137,17)
COLOR_COL_RIGHT = (67,140,18)

PLAYER_1_COLOR = GREEN
PLAYER_2_COLOR = YELLOW

B_1 = 1
B_2 = 2
B_3 = 3
B_4 = 4
B_5 = 5
B_6 = 6
LEFT = 7
RIGHT = 8
UP = 9
DOWN = 10